# Generated by Django 5.0.6 on 2024-05-28 19:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pessoas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=20)),
                ("idade", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Produtos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=20)),
                ("categoria", models.CharField(max_length=20)),
                ("preco", models.IntegerField()),
                ("quantidade", models.IntegerField()),
                ("codigo", models.CharField(max_length=20)),
                ("descricao", models.TextField()),
            ],
        ),
    ]
