# Generated by Django 5.0.6 on 2024-05-10 02:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("choperia", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="categoria",
            name="data_pub",
        ),
        migrations.AddField(
            model_name="categoria",
            name="data_criacao",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="data de criação"
            ),
            preserve_default=False,
        ),
    ]
