# Generated by Django 5.0.6 on 2024-05-13 02:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("choperia", "0002_remove_categoria_data_pub_categoria_data_criacao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="estoque",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="produto",
            name="estoque_total",
            field=models.IntegerField(default=0),
        ),
    ]
