# Generated by Django 5.0.6 on 2024-05-17 11:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("choperia", "0003_alter_produto_estoque_alter_produto_estoque_total"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="descricao",
            field=models.TextField(blank=True),
        ),
    ]
