# Generated by Django 5.0.6 on 2024-05-09 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("categoria", models.CharField(max_length=50)),
                ("data_pub", models.DateTimeField(verbose_name="data de publicação")),
            ],
        ),
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_text", models.CharField(max_length=50)),
                ("descricao", models.TextField()),
                ("custo", models.DecimalField(decimal_places=2, max_digits=10)),
                ("venda", models.DecimalField(decimal_places=2, max_digits=10)),
                ("codigo", models.IntegerField()),
                ("estoque", models.IntegerField()),
                ("estoque_total", models.IntegerField()),
                ("imagem", models.ImageField(upload_to="imagens/")),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="choperia.categoria",
                    ),
                ),
            ],
        ),
    ]
