# Generated by Django 5.0.6 on 2024-05-09 04:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("choperia", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="categoria",
            old_name="categoria",
            new_name="categoria_text",
        ),
        migrations.RenameField(
            model_name="produto",
            old_name="nome_text",
            new_name="nome_produto",
        ),
    ]
