# Generated by Django 5.0.4 on 2024-04-28 15:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="imagem",
            field=models.ImageField(null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="produto",
            name="preco",
            field=models.IntegerField(),
        ),
    ]
