# Generated by Django 5.0.6 on 2024-06-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("categoria", models.CharField(max_length=50)),
                ("nome_produto", models.CharField(max_length=50)),
                ("descricao", models.TextField(blank=True)),
                ("custo", models.DecimalField(decimal_places=2, max_digits=10)),
                ("venda", models.DecimalField(decimal_places=2, max_digits=10)),
                ("codigo", models.IntegerField()),
                ("estoque", models.IntegerField(default=0)),
                ("estoque_total", models.IntegerField(default=0)),
                ("imagem", models.ImageField(upload_to="imagens/")),
            ],
        ),
    ]
