# Generated by Django 5.0.6 on 2024-06-19 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('itens', models.JSONField(default=list)),
                ('status', models.CharField(default='Fechada', max_length=10)),
                ('pedido', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=50)),
                ('descricao', models.TextField(blank=True)),
                ('custo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('venda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('codigo', models.IntegerField()),
                ('estoque', models.IntegerField(default=0)),
                ('estoque_total', models.IntegerField(default=0)),
                ('imagem', models.ImageField(upload_to='imagens/')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ap_cho.categoria')),
            ],
        ),
    ]
