# Generated by Django 5.0.6 on 2024-06-24 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(max_length=20, verbose_name='Série')),
                ('numero', models.PositiveIntegerField(verbose_name='Número')),
                ('descricao', models.CharField(max_length=255, verbose_name='Nome/Descrição')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Peso (kg)')),
                ('cubagem', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Cubagem (m³)')),
                ('data_emissao', models.DateField(verbose_name='Data de Emissão')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_fiscais', to='empresa.empresa')),
            ],
        ),
    ]
